# UFormer Star Removal - RTX 5090 OPTIMIZED

experiment:
  name: "uformer_5090_optimized"
  output_dir: "experiments"

data:
  train_input_dir: "train_tiles/input"
  train_target_dir: "train_tiles/target" 
  val_input_dir: "val_tiles/input"
  val_target_dir: "val_tiles/target"

model:
  embed_dim: 96
  win_size: 8                    # Mantiene finestre piccole per inferenza leggera
  depths: [2, 2, 6, 2]          # Profondità maggiore nel livello centrale
  num_heads: [3, 6, 12, 24]
  shifted_window: true          # ESSENZIALE: elimina quadretti 8x8
  halo_size: 4                  # Proporzionale al win_size
  focal_interval: 999           # DISABILITA focal blocks temporaneamente

training:
  epochs: 300
  batch_size: 10  # Ottimizzato per RTX 5090 24GB
  val_batch_size: 20
  num_workers: 4
  val_subset_size: 1000
  
  optimizer:
    name: "adamw"
    lr: 0.0002
    weight_decay: 0.01
    betas: [0.9, 0.999]
  
  scheduler:
    name: "cosineannealinglr"
    eta_min: 0.000001
  
  compile_model: false
  log_interval: 10
  save_interval: 1

# Resume from checkpoint
resume_checkpoint: "best_model.pth"

# Balanced Loss - ridotto perceptual weight per memoria
loss:
  l1_weight: 1.0              # Base L1 loss
  perceptual_weight: 0.05     # RIDOTTO da 0.1 per memoria
  ssim_weight: 0.05           # RIDOTTO da 0.1 per memoria
  mask_weight: 0.1